# Generated by Django 4.2.1 on 2023-05-06 02:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_id_alter_userprofile_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="description",
            new_name="bio",
        ),
    ]
