# Generated by Django 4.2.1 on 2023-05-06 03:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_description_userprofile_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="is_organizer",
        ),
    ]
